# Generated by Django 5.2.7 on 2025-12-08 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='phone_name',
            new_name='phone',
        ),
    ]
